# Generated by Django 4.1.7 on 2023-04-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_domainsmodel'),
        ('templatesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebsites',
            name='domain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersapp.domainsmodel'),
        ),
        migrations.AddField(
            model_name='userwebsites',
            name='status',
            field=models.TextField(choices=[('draft', 'DRAFT'), ('published', 'PUBLISHED')], default='draft'),
        ),
    ]
