# Generated by Django 4.1.7 on 2023-04-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesapp', '0002_userwebsites_domain_userwebsites_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='templatesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
            ],
        ),
    ]
