# Generated by Django 4.1.7 on 2023-04-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesapp', '0004_alter_userwebsites_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesmodel',
            name='head',
            field=models.TextField(default=''),
        ),
    ]
