# Generated by Django 4.1.7 on 2023-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesapp', '0006_userwebsites_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesmodel',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='templatesmodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
