# Generated by Django 4.1.7 on 2023-06-20 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='file',
            field=models.FileField(default='', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
